# Generated by Django 5.1.1 on 2024-10-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_rename_liked_by_tip_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='social_media_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
